name: Convert
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
      # Python
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      # Get all resources
      - uses: actions/checkout@v3
        with:
          repository: ArchivesNationalesFR/Referentiels
          path: Referentiels
          ref: version_2
          run: |
            python convertToJson.py --generate READ --input Referentiels --output garance_python.json
      
      #- name: Python Process
      #  env: 
      #    GaranceRepo: "/home/runner/work/demo_python/demo_python/Referentiels"
      #  run: |
      #    python convertToJson.py --generate READ --input $GaranceRepo --output garance_python.json
