name: Convert
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Get all resources
      - uses: actions/checkout@v3
        with:
          repository: ArchivesNationalesFR/Referentiels
          path: Referentiels
          ref: version_2

      - name: Lire les fichiers
        run: |
          pwd Referentiels
          ls -l ${GITHUB_WORKSPACE}/Referentiels
      
      # Python
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Python Process
        run: |
          python convertToJson.py --generate READ --input ${GITHUB_WORKSPACE}/Referentiels --output garance_python.json
